#! /bin/sh

# Script to sort quinn diff output by section then priority.
# Copyright (C) 1997, 1998 James Troup <james@nocrew.org>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

set -e

tmpfile=$(mktemp /tmp/$(basename $0).XXXXXX)

trap 'rm -f $tmpfile ; exit 1' 1 2 3 13 15

quinn-diff > $tmpfile

sections="base admin comm devel doc editors electronics games graphics hamradio interpreters libs mail math misc net news oldlibs otherosfs shells sound tex text utils web x11"

for i in $sections; do
  egrep "$i\/.*\[required\:" $tmpfile | sort
  egrep "$i\/.*\[important\:" $tmpfile | sort
  egrep "$i\/.*\[standard\:" $tmpfile | sort
  egrep "$i\/.*\[optional\:" $tmpfile | sort
  egrep "$i\/.*\[extra\:" $tmpfile | sort
done
egrep -v "\[extra\:|\[optional\:|\[standard\:|\[important\:|\[required\:" $tmpfile | sort

rm -f $tmpfile
exit 0
